deployment:
       tasks:
         - export DEPLOYPATH=/home/lorvenho/public_html/
         - /bin/cp -R .vscode $DEPLOYPATH
         - /bin/cp -R assets $DEPLOYPATH
         - /bin/cp -R css $DEPLOYPATH
